/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'isArchived' : IDL.Bool,
  'programId' : IDL.Text,
  'orphanageId' : IDL.Opt(IDL.Text),
});
export const DocumentationEntry = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'activityId' : IDL.Text,
  'isArchived' : IDL.Bool,
  'isActive' : IDL.Bool,
  'author' : IDL.Text,
  'timestamp' : IDL.Nat,
  'idText' : IDL.Text,
});
export const Orphanage = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'constraints' : IDL.Text,
  'secondaryContact' : IDL.Opt(IDL.Text),
  'currentOccupancy' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'address' : IDL.Text,
  'capacity' : IDL.Nat,
  'internalNotes' : IDL.Text,
  'demographicNotes' : IDL.Text,
  'primaryContact' : IDL.Text,
  'priorityNeeds' : IDL.Text,
});
export const Person = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isArchived' : IDL.Bool,
  'isActive' : IDL.Bool,
  'idText' : IDL.Text,
});
export const Program = IDL.Record({
  'id' : IDL.Text,
  'resources' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isArchived' : IDL.Bool,
  'evaluationCriteria' : IDL.Text,
  'regulations' : IDL.Text,
  'schedule' : IDL.Text,
  'budget' : IDL.Text,
  'targetParticipants' : IDL.Text,
  'objectives' : IDL.Text,
  'sponsors' : IDL.Text,
});
export const ScheduleEvent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isArchived' : IDL.Bool,
  'endTimestamp' : IDL.Nat,
  'startTimestamp' : IDL.Nat,
  'programId' : IDL.Text,
  'location' : IDL.Opt(IDL.Text),
});
export const KidProfile = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'programIds' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'caretakerId' : IDL.Principal,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const TimelineEvent = IDL.Record({
  'id' : IDL.Nat,
  'timestamp' : IDL.Nat,
  'details' : IDL.Opt(IDL.Text),
  'actorPrincipal' : IDL.Opt(IDL.Principal),
  'programId' : IDL.Text,
  'relatedId' : IDL.Opt(IDL.Text),
  'eventType' : IDL.Text,
});
export const MediaAttachment = IDL.Record({
  'id' : IDL.Text,
  'contentType' : IDL.Text,
  'byteSize' : IDL.Nat,
  'isImage' : IDL.Bool,
  'isArchived' : IDL.Bool,
  'filename' : IDL.Text,
  'uploadedAt' : IDL.Nat,
  'uploadedBy' : IDL.Principal,
});
export const ActivityAttachment = IDL.Record({
  'metadata' : MediaAttachment,
  'activityId' : IDL.Text,
  'programId' : IDL.Text,
});
export const DocumentationAttachment = IDL.Record({
  'metadata' : MediaAttachment,
  'documentationId' : IDL.Nat,
  'programId' : IDL.Text,
});
export const MediaAttachmentUpload = IDL.Record({
  'id' : IDL.Text,
  'contentType' : IDL.Text,
  'byteSize' : IDL.Nat,
  'isImage' : IDL.Bool,
  'filename' : IDL.Text,
  'fileBytes' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGarbageCollectAttachments' : IDL.Func([IDL.Null], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignProgramToKid' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'clearKidContext' : IDL.Func([], [], []),
  'createActivity' : IDL.Func([Activity], [IDL.Text], []),
  'createDocumentationEntry' : IDL.Func([DocumentationEntry], [IDL.Nat], []),
  'createKidProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'createOrphanage' : IDL.Func([Orphanage], [IDL.Text], []),
  'createPerson' : IDL.Func([Person], [IDL.Nat], []),
  'createProgram' : IDL.Func([Program], [IDL.Text], []),
  'createScheduleEvent' : IDL.Func([ScheduleEvent], [IDL.Text], []),
  'deleteActivity' : IDL.Func([IDL.Text], [], []),
  'deleteActivityAttachment' : IDL.Func([IDL.Text], [], []),
  'deleteDocumentationAttachment' : IDL.Func([IDL.Text], [], []),
  'deleteDocumentationEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteKidProfile' : IDL.Func([IDL.Text], [], []),
  'deleteOrphanage' : IDL.Func([IDL.Text], [], []),
  'deletePerson' : IDL.Func([IDL.Nat], [], []),
  'deleteProgram' : IDL.Func([IDL.Text], [], []),
  'deleteProgramMediaAttachment' : IDL.Func([IDL.Text], [], []),
  'deleteScheduleEvent' : IDL.Func([IDL.Text], [], []),
  'getActiveKidContext' : IDL.Func([], [IDL.Opt(KidProfile)], ['query']),
  'getActivity' : IDL.Func([IDL.Text], [IDL.Opt(Activity)], ['query']),
  'getActivityAttachmentFile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocumentationAttachmentFile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getKidProfile' : IDL.Func([IDL.Text], [IDL.Opt(KidProfile)], ['query']),
  'getOrphanage' : IDL.Func([IDL.Text], [IDL.Opt(Orphanage)], ['query']),
  'getProgram' : IDL.Func([IDL.Text], [IDL.Opt(Program)], ['query']),
  'getProgramMediaAttachmentFile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getProgramTimeline' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TimelineEvent)],
      ['query'],
    ),
  'getUpcomingEventsInWindow' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(ScheduleEvent)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'listActivityAttachments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ActivityAttachment)],
      ['query'],
    ),
  'listDocumentationAttachments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DocumentationAttachment)],
      ['query'],
    ),
  'listDocumentationEntries' : IDL.Func(
      [],
      [IDL.Vec(DocumentationEntry)],
      ['query'],
    ),
  'listMyKidProfiles' : IDL.Func([], [IDL.Vec(KidProfile)], ['query']),
  'listOrphanages' : IDL.Func([], [IDL.Vec(Orphanage)], ['query']),
  'listPeople' : IDL.Func([], [IDL.Vec(Person)], ['query']),
  'listProgramMediaAttachments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MediaAttachment)],
      ['query'],
    ),
  'listPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
  'listScheduleEvents' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ScheduleEvent)],
      ['query'],
    ),
  'removeProgramFromKid' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selectKidContext' : IDL.Func([IDL.Text], [], []),
  'updateActivity' : IDL.Func([IDL.Text, Activity], [], []),
  'updateDocumentationEntry' : IDL.Func([IDL.Nat, DocumentationEntry], [], []),
  'updateOrphanage' : IDL.Func([IDL.Text, Orphanage], [], []),
  'updatePerson' : IDL.Func([IDL.Nat, Person], [], []),
  'updateProgram' : IDL.Func([IDL.Text, Program], [], []),
  'updateScheduleEvent' : IDL.Func([IDL.Text, ScheduleEvent], [], []),
  'uploadActivityAttachment' : IDL.Func(
      [IDL.Text, MediaAttachmentUpload],
      [IDL.Text],
      [],
    ),
  'uploadDocumentationAttachment' : IDL.Func(
      [IDL.Nat, IDL.Text, MediaAttachmentUpload],
      [IDL.Text],
      [],
    ),
  'uploadProgramMediaAttachment' : IDL.Func(
      [MediaAttachmentUpload],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Activity = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'isArchived' : IDL.Bool,
    'programId' : IDL.Text,
    'orphanageId' : IDL.Opt(IDL.Text),
  });
  const DocumentationEntry = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'activityId' : IDL.Text,
    'isArchived' : IDL.Bool,
    'isActive' : IDL.Bool,
    'author' : IDL.Text,
    'timestamp' : IDL.Nat,
    'idText' : IDL.Text,
  });
  const Orphanage = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'constraints' : IDL.Text,
    'secondaryContact' : IDL.Opt(IDL.Text),
    'currentOccupancy' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'address' : IDL.Text,
    'capacity' : IDL.Nat,
    'internalNotes' : IDL.Text,
    'demographicNotes' : IDL.Text,
    'primaryContact' : IDL.Text,
    'priorityNeeds' : IDL.Text,
  });
  const Person = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isArchived' : IDL.Bool,
    'isActive' : IDL.Bool,
    'idText' : IDL.Text,
  });
  const Program = IDL.Record({
    'id' : IDL.Text,
    'resources' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isArchived' : IDL.Bool,
    'evaluationCriteria' : IDL.Text,
    'regulations' : IDL.Text,
    'schedule' : IDL.Text,
    'budget' : IDL.Text,
    'targetParticipants' : IDL.Text,
    'objectives' : IDL.Text,
    'sponsors' : IDL.Text,
  });
  const ScheduleEvent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isArchived' : IDL.Bool,
    'endTimestamp' : IDL.Nat,
    'startTimestamp' : IDL.Nat,
    'programId' : IDL.Text,
    'location' : IDL.Opt(IDL.Text),
  });
  const KidProfile = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'programIds' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'caretakerId' : IDL.Principal,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const TimelineEvent = IDL.Record({
    'id' : IDL.Nat,
    'timestamp' : IDL.Nat,
    'details' : IDL.Opt(IDL.Text),
    'actorPrincipal' : IDL.Opt(IDL.Principal),
    'programId' : IDL.Text,
    'relatedId' : IDL.Opt(IDL.Text),
    'eventType' : IDL.Text,
  });
  const MediaAttachment = IDL.Record({
    'id' : IDL.Text,
    'contentType' : IDL.Text,
    'byteSize' : IDL.Nat,
    'isImage' : IDL.Bool,
    'isArchived' : IDL.Bool,
    'filename' : IDL.Text,
    'uploadedAt' : IDL.Nat,
    'uploadedBy' : IDL.Principal,
  });
  const ActivityAttachment = IDL.Record({
    'metadata' : MediaAttachment,
    'activityId' : IDL.Text,
    'programId' : IDL.Text,
  });
  const DocumentationAttachment = IDL.Record({
    'metadata' : MediaAttachment,
    'documentationId' : IDL.Nat,
    'programId' : IDL.Text,
  });
  const MediaAttachmentUpload = IDL.Record({
    'id' : IDL.Text,
    'contentType' : IDL.Text,
    'byteSize' : IDL.Nat,
    'isImage' : IDL.Bool,
    'filename' : IDL.Text,
    'fileBytes' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGarbageCollectAttachments' : IDL.Func([IDL.Null], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignProgramToKid' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'clearKidContext' : IDL.Func([], [], []),
    'createActivity' : IDL.Func([Activity], [IDL.Text], []),
    'createDocumentationEntry' : IDL.Func([DocumentationEntry], [IDL.Nat], []),
    'createKidProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'createOrphanage' : IDL.Func([Orphanage], [IDL.Text], []),
    'createPerson' : IDL.Func([Person], [IDL.Nat], []),
    'createProgram' : IDL.Func([Program], [IDL.Text], []),
    'createScheduleEvent' : IDL.Func([ScheduleEvent], [IDL.Text], []),
    'deleteActivity' : IDL.Func([IDL.Text], [], []),
    'deleteActivityAttachment' : IDL.Func([IDL.Text], [], []),
    'deleteDocumentationAttachment' : IDL.Func([IDL.Text], [], []),
    'deleteDocumentationEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteKidProfile' : IDL.Func([IDL.Text], [], []),
    'deleteOrphanage' : IDL.Func([IDL.Text], [], []),
    'deletePerson' : IDL.Func([IDL.Nat], [], []),
    'deleteProgram' : IDL.Func([IDL.Text], [], []),
    'deleteProgramMediaAttachment' : IDL.Func([IDL.Text], [], []),
    'deleteScheduleEvent' : IDL.Func([IDL.Text], [], []),
    'getActiveKidContext' : IDL.Func([], [IDL.Opt(KidProfile)], ['query']),
    'getActivity' : IDL.Func([IDL.Text], [IDL.Opt(Activity)], ['query']),
    'getActivityAttachmentFile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocumentationAttachmentFile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getKidProfile' : IDL.Func([IDL.Text], [IDL.Opt(KidProfile)], ['query']),
    'getOrphanage' : IDL.Func([IDL.Text], [IDL.Opt(Orphanage)], ['query']),
    'getProgram' : IDL.Func([IDL.Text], [IDL.Opt(Program)], ['query']),
    'getProgramMediaAttachmentFile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getProgramTimeline' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimelineEvent)],
        ['query'],
      ),
    'getUpcomingEventsInWindow' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(ScheduleEvent)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'listActivityAttachments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ActivityAttachment)],
        ['query'],
      ),
    'listDocumentationAttachments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DocumentationAttachment)],
        ['query'],
      ),
    'listDocumentationEntries' : IDL.Func(
        [],
        [IDL.Vec(DocumentationEntry)],
        ['query'],
      ),
    'listMyKidProfiles' : IDL.Func([], [IDL.Vec(KidProfile)], ['query']),
    'listOrphanages' : IDL.Func([], [IDL.Vec(Orphanage)], ['query']),
    'listPeople' : IDL.Func([], [IDL.Vec(Person)], ['query']),
    'listProgramMediaAttachments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MediaAttachment)],
        ['query'],
      ),
    'listPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
    'listScheduleEvents' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScheduleEvent)],
        ['query'],
      ),
    'removeProgramFromKid' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selectKidContext' : IDL.Func([IDL.Text], [], []),
    'updateActivity' : IDL.Func([IDL.Text, Activity], [], []),
    'updateDocumentationEntry' : IDL.Func(
        [IDL.Nat, DocumentationEntry],
        [],
        [],
      ),
    'updateOrphanage' : IDL.Func([IDL.Text, Orphanage], [], []),
    'updatePerson' : IDL.Func([IDL.Nat, Person], [], []),
    'updateProgram' : IDL.Func([IDL.Text, Program], [], []),
    'updateScheduleEvent' : IDL.Func([IDL.Text, ScheduleEvent], [], []),
    'uploadActivityAttachment' : IDL.Func(
        [IDL.Text, MediaAttachmentUpload],
        [IDL.Text],
        [],
      ),
    'uploadDocumentationAttachment' : IDL.Func(
        [IDL.Nat, IDL.Text, MediaAttachmentUpload],
        [IDL.Text],
        [],
      ),
    'uploadProgramMediaAttachment' : IDL.Func(
        [MediaAttachmentUpload],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };