/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : string,
  'status' : string,
  'title' : string,
  'owner' : Principal,
  'isArchived' : boolean,
  'programId' : string,
  'orphanageId' : [] | [string],
}
export interface DocumentationEntry {
  'id' : bigint,
  'content' : string,
  'activityId' : string,
  'isArchived' : boolean,
  'isActive' : boolean,
  'author' : string,
  'timestamp' : bigint,
  'idText' : string,
}
export interface KidProfile {
  'id' : string,
  'age' : bigint,
  'programIds' : Array<string>,
  'isActive' : boolean,
  'caretakerId' : Principal,
  'lastName' : string,
  'firstName' : string,
}
export interface MediaAttachmentUpload {
  'id' : string,
  'contentType' : string,
  'byteSize' : bigint,
  'isImage' : boolean,
  'filename' : string,
  'fileBytes' : Uint8Array,
  'programId' : string,
}
export interface Orphanage {
  'id' : string,
  'region' : string,
  'constraints' : string,
  'secondaryContact' : [] | [string],
  'currentOccupancy' : bigint,
  'name' : string,
  'isActive' : boolean,
  'address' : string,
  'capacity' : bigint,
  'internalNotes' : string,
  'demographicNotes' : string,
  'primaryContact' : string,
  'priorityNeeds' : string,
}
export interface Person {
  'id' : bigint,
  'contact' : string,
  'name' : string,
  'role' : string,
  'isArchived' : boolean,
  'isActive' : boolean,
  'idText' : string,
}
export interface Program {
  'id' : string,
  'resources' : string,
  'name' : string,
  'description' : string,
  'isArchived' : boolean,
  'evaluationCriteria' : string,
  'regulations' : string,
  'schedule' : string,
  'budget' : string,
  'targetParticipants' : string,
  'objectives' : string,
  'sponsors' : string,
}
export interface ProgramMediaAttachment {
  'id' : string,
  'contentType' : string,
  'byteSize' : bigint,
  'isImage' : boolean,
  'isArchived' : boolean,
  'filename' : string,
  'programId' : string,
  'uploadedAt' : bigint,
  'uploadedBy' : Principal,
}
export interface ScheduleEvent {
  'id' : string,
  'title' : string,
  'description' : string,
  'isArchived' : boolean,
  'endTimestamp' : bigint,
  'startTimestamp' : bigint,
  'programId' : string,
  'location' : [] | [string],
}
export interface TimelineEvent {
  'id' : bigint,
  'timestamp' : bigint,
  'details' : [] | [string],
  'actorPrincipal' : [] | [Principal],
  'programId' : string,
  'relatedId' : [] | [string],
  'eventType' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignProgramToKid' : ActorMethod<[string, string], undefined>,
  'clearKidContext' : ActorMethod<[], undefined>,
  'createActivity' : ActorMethod<[Activity], string>,
  'createDocumentationEntry' : ActorMethod<[DocumentationEntry], bigint>,
  'createKidProfile' : ActorMethod<[string, string, bigint], string>,
  'createOrphanage' : ActorMethod<[Orphanage], string>,
  'createPerson' : ActorMethod<[Person], bigint>,
  'createProgram' : ActorMethod<[Program], string>,
  'createScheduleEvent' : ActorMethod<[ScheduleEvent], string>,
  'deleteActivity' : ActorMethod<[string], undefined>,
  'deleteDocumentationEntry' : ActorMethod<[bigint], undefined>,
  'deleteKidProfile' : ActorMethod<[string], undefined>,
  'deleteOrphanage' : ActorMethod<[string], undefined>,
  'deletePerson' : ActorMethod<[bigint], undefined>,
  'deleteProgram' : ActorMethod<[string], undefined>,
  'deleteProgramMediaAttachment' : ActorMethod<[string], undefined>,
  'deleteScheduleEvent' : ActorMethod<[string], undefined>,
  'getActiveKidContext' : ActorMethod<[], [] | [KidProfile]>,
  'getActivity' : ActorMethod<[string], [] | [Activity]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKidProfile' : ActorMethod<[string], [] | [KidProfile]>,
  'getOrphanage' : ActorMethod<[string], [] | [Orphanage]>,
  'getProgram' : ActorMethod<[string], [] | [Program]>,
  'getProgramTimeline' : ActorMethod<[string], Array<TimelineEvent>>,
  'getUpcomingEventsInWindow' : ActorMethod<
    [[] | [bigint]],
    Array<ScheduleEvent>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActivities' : ActorMethod<[], Array<Activity>>,
  'listDocumentationEntries' : ActorMethod<[], Array<DocumentationEntry>>,
  'listMyKidProfiles' : ActorMethod<[], Array<KidProfile>>,
  'listOrphanages' : ActorMethod<[], Array<Orphanage>>,
  'listPeople' : ActorMethod<[], Array<Person>>,
  'listProgramMediaAttachments' : ActorMethod<
    [string],
    Array<ProgramMediaAttachment>
  >,
  'listPrograms' : ActorMethod<[], Array<Program>>,
  'listScheduleEvents' : ActorMethod<[string], Array<ScheduleEvent>>,
  'removeProgramFromKid' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selectKidContext' : ActorMethod<[string], undefined>,
  'updateActivity' : ActorMethod<[string, Activity], undefined>,
  'updateDocumentationEntry' : ActorMethod<
    [bigint, DocumentationEntry],
    undefined
  >,
  'updateOrphanage' : ActorMethod<[string, Orphanage], undefined>,
  'updatePerson' : ActorMethod<[bigint, Person], undefined>,
  'updateProgram' : ActorMethod<[string, Program], undefined>,
  'updateScheduleEvent' : ActorMethod<[string, ScheduleEvent], undefined>,
  'uploadProgramMediaAttachment' : ActorMethod<[MediaAttachmentUpload], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];