import { Program, Activity, Orphanage } from '../backend';
import { Principal } from '@dfinity/principal';

export const samplePrograms: Program[] = [
  {
    id: 'sample-prog-1',
    name: 'Adab & Fitrah Exploration',
    description: 'Learning Islamic values through thematic activities, storytelling, roleplay, and real-life simulations. Focuses on building strong character and understanding of tauhid.',
    objectives: 'Develop understanding of Islamic values, build strong character, and foster understanding of tauhid through experiential learning.',
    targetParticipants: 'Children ages 7-14 from orphanages, with basic Islamic knowledge.',
    schedule: 'Monthly sessions, 3 hours per session, typically on weekends.',
    resources: 'Storybooks, roleplay materials, activity worksheets, Islamic teaching aids.',
    evaluationCriteria: 'Participant engagement, behavioral improvements, understanding of core concepts through assessments.',
    budget: 'Rp 2,000,000 per session (materials, facilitator fees, snacks).',
    sponsors: 'Local Islamic foundations, community donors.',
    regulations: 'Parental consent required, adherence to Islamic teaching standards, child safety protocols.',
    isArchived: false,
  },
  {
    id: 'sample-prog-2',
    name: 'Ramadan Micro Camp',
    description: 'Intensive one-day program during Ramadan that strengthens values, courage, and independence through structured activities and reflection.',
    objectives: 'Strengthen Islamic values during Ramadan, build courage and independence, create memorable spiritual experiences.',
    targetParticipants: 'Children ages 8-16 from partner orphanages, physically able to participate in day-long activities.',
    schedule: 'One full day during Ramadan (8 AM - 5 PM), typically mid-Ramadan.',
    resources: 'Outdoor venue, camping equipment, activity materials, meals for iftar, Islamic learning materials.',
    evaluationCriteria: 'Participant feedback, completion of activities, spiritual reflection quality, behavioral observations.',
    budget: 'Rp 5,000,000 per camp (venue, meals, materials, facilitators).',
    sponsors: 'Corporate CSR programs, Islamic charities.',
    regulations: 'Medical clearance for participants, emergency protocols, fasting accommodation, prayer time scheduling.',
    isArchived: false,
  },
  {
    id: 'sample-prog-3',
    name: 'Life Skills & Curiosity',
    description: 'Hands-on experiments, simple projects, and discussions that develop critical thinking and curiosity about the world.',
    objectives: 'Foster curiosity and critical thinking, develop practical life skills, encourage scientific inquiry and problem-solving.',
    targetParticipants: 'Children ages 9-15 with interest in science and hands-on learning.',
    schedule: 'Bi-weekly sessions, 2.5 hours per session, flexible scheduling.',
    resources: 'Science experiment kits, project materials, safety equipment, reference books, workspace.',
    evaluationCriteria: 'Project completion, problem-solving ability, curiosity indicators, skill development progress.',
    budget: 'Rp 1,500,000 per session (materials, facilitator fees).',
    sponsors: 'Education foundations, STEM-focused donors.',
    regulations: 'Safety protocols for experiments, age-appropriate activities, supervision requirements.',
    isArchived: false,
  },
];

export const sampleOrphanages: Orphanage[] = [
  {
    id: 'sample-orph-1',
    name: 'Panti Asuhan Al-Ikhlas',
    address: 'Jl. Raya Bogor KM 25, Cimanggis',
    region: 'Depok, Jawa Barat',
    primaryContact: '+62 812-3456-7890',
    secondaryContact: 'alikhlas@example.com',
    capacity: BigInt(50),
    currentOccupancy: BigInt(42),
    demographicNotes: 'Ages 6-17, mixed gender. 15 children with special learning needs. Strong interest in STEM activities.',
    constraints: 'Limited outdoor space. Activities must end by 4 PM for prayer time. No activities during exam weeks (June, December).',
    priorityNeeds: 'Educational materials, mentorship programs, life skills training, career guidance for older children.',
    internalNotes: 'Very responsive management. Previous Ramadan camp was highly successful. Director prefers 2-week advance notice.',
    isActive: true,
  },
  {
    id: 'sample-orph-2',
    name: 'Yayasan Kasih Anak Bangsa',
    address: 'Jl. Mawar No. 15, Kebayoran Baru',
    region: 'Jakarta Selatan',
    primaryContact: '+62 821-9876-5432',
    secondaryContact: undefined,
    capacity: BigInt(35),
    currentOccupancy: BigInt(28),
    demographicNotes: 'Ages 5-15, predominantly girls. Several children from underprivileged backgrounds with strong academic potential.',
    constraints: 'Small facility, max 20 participants per session. Weekend programs preferred. Need 1 month advance booking.',
    priorityNeeds: 'Reading materials, art supplies, confidence-building programs, female role models and mentors.',
    internalNotes: 'New partnership. First activity scheduled for next quarter. Very enthusiastic about collaboration.',
    isActive: true,
  },
];

export const sampleActivities: Activity[] = [
  {
    id: 'sample-act-1',
    title: 'Ramadan Camp at Panti Asuhan Al-Ikhlas',
    status: 'Completed',
    programId: 'sample-prog-2',
    orphanageId: 'sample-orph-1',
    isArchived: false,
    owner: Principal.anonymous(),
  },
  {
    id: 'sample-act-2',
    title: 'Adab Workshop - Understanding Respect',
    status: 'Scheduled',
    programId: 'sample-prog-1',
    orphanageId: 'sample-orph-2',
    isArchived: false,
    owner: Principal.anonymous(),
  },
  {
    id: 'sample-act-3',
    title: 'Science Exploration Day',
    status: 'Planning',
    programId: 'sample-prog-3',
    orphanageId: undefined,
    isArchived: false,
    owner: Principal.anonymous(),
  },
];
