/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProgramMediaAttachment {
    id: string;
    contentType: string;
    byteSize: bigint;
    isImage: boolean;
    isArchived: boolean;
    filename: string;
    programId: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
}
export interface MediaAttachmentUpload {
    id: string;
    contentType: string;
    byteSize: bigint;
    isImage: boolean;
    filename: string;
    fileBytes: Uint8Array;
    programId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Orphanage {
    id: string;
    region: string;
    constraints: string;
    secondaryContact?: string;
    currentOccupancy: bigint;
    name: string;
    isActive: boolean;
    address: string;
    capacity: bigint;
    internalNotes: string;
    demographicNotes: string;
    primaryContact: string;
    priorityNeeds: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ScheduleEvent {
    id: string;
    title: string;
    description: string;
    isArchived: boolean;
    endTimestamp: bigint;
    startTimestamp: bigint;
    programId: string;
    location?: string;
}
export interface KidProfile {
    id: string;
    age: bigint;
    programIds: Array<string>;
    isActive: boolean;
    caretakerId: Principal;
    lastName: string;
    firstName: string;
}
export interface DocumentationEntry {
    id: bigint;
    content: string;
    activityId: string;
    isArchived: boolean;
    isActive: boolean;
    author: string;
    timestamp: bigint;
    idText: string;
}
export interface Activity {
    id: string;
    status: string;
    title: string;
    owner: Principal;
    isArchived: boolean;
    programId: string;
    orphanageId?: string;
}
export interface Program {
    id: string;
    resources: string;
    name: string;
    description: string;
    isArchived: boolean;
    evaluationCriteria: string;
    regulations: string;
    schedule: string;
    budget: string;
    targetParticipants: string;
    objectives: string;
    sponsors: string;
}
export interface Person {
    id: bigint;
    contact: string;
    name: string;
    role: string;
    isArchived: boolean;
    isActive: boolean;
    idText: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignProgramToKid(kidId: string, programId: string): Promise<void>;
    clearKidContext(): Promise<void>;
    createActivity(activity: Activity): Promise<string>;
    createDocumentationEntry(entry: DocumentationEntry): Promise<bigint>;
    createKidProfile(firstName: string, lastName: string, age: bigint): Promise<string>;
    createOrphanage(orphanage: Orphanage): Promise<string>;
    createPerson(person: Person): Promise<bigint>;
    createProgram(program: Program): Promise<string>;
    createScheduleEvent(event: ScheduleEvent): Promise<string>;
    deleteActivity(id: string): Promise<void>;
    deleteDocumentationEntry(id: bigint): Promise<void>;
    deleteKidProfile(id: string): Promise<void>;
    deleteOrphanage(id: string): Promise<void>;
    deletePerson(id: bigint): Promise<void>;
    deleteProgram(id: string): Promise<void>;
    deleteProgramMediaAttachment(id: string): Promise<void>;
    deleteScheduleEvent(id: string): Promise<void>;
    getActiveKidContext(): Promise<KidProfile | null>;
    getActivity(id: string): Promise<Activity | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getKidProfile(id: string): Promise<KidProfile | null>;
    getOrphanage(id: string): Promise<Orphanage | null>;
    getProgram(id: string): Promise<Program | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listActivities(): Promise<Array<Activity>>;
    listDocumentationEntries(): Promise<Array<DocumentationEntry>>;
    listMyKidProfiles(): Promise<Array<KidProfile>>;
    listOrphanages(): Promise<Array<Orphanage>>;
    listPeople(): Promise<Array<Person>>;
    listProgramMediaAttachments(programId: string): Promise<Array<ProgramMediaAttachment>>;
    listPrograms(): Promise<Array<Program>>;
    listScheduleEvents(programId: string): Promise<Array<ScheduleEvent>>;
    removeProgramFromKid(kidId: string, programId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    selectKidContext(kidId: string): Promise<void>;
    updateActivity(id: string, activity: Activity): Promise<void>;
    updateDocumentationEntry(id: bigint, entry: DocumentationEntry): Promise<void>;
    updateOrphanage(id: string, orphanage: Orphanage): Promise<void>;
    updatePerson(id: bigint, person: Person): Promise<void>;
    updateProgram(id: string, program: Program): Promise<void>;
    updateScheduleEvent(id: string, event: ScheduleEvent): Promise<void>;
    uploadProgramMediaAttachment(upload: MediaAttachmentUpload): Promise<string>;
}
import type { Activity as _Activity, KidProfile as _KidProfile, Orphanage as _Orphanage, Program as _Program, ScheduleEvent as _ScheduleEvent, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignProgramToKid(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignProgramToKid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignProgramToKid(arg0, arg1);
            return result;
        }
    }
    async clearKidContext(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearKidContext();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearKidContext();
            return result;
        }
    }
    async createActivity(arg0: Activity): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createActivity(to_candid_Activity_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createActivity(to_candid_Activity_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createDocumentationEntry(arg0: DocumentationEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocumentationEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocumentationEntry(arg0);
            return result;
        }
    }
    async createKidProfile(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createKidProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createKidProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrphanage(arg0: Orphanage): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrphanage(to_candid_Orphanage_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrphanage(to_candid_Orphanage_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPerson(arg0: Person): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPerson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPerson(arg0);
            return result;
        }
    }
    async createProgram(arg0: Program): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createProgram(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProgram(arg0);
            return result;
        }
    }
    async createScheduleEvent(arg0: ScheduleEvent): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createScheduleEvent(to_candid_ScheduleEvent_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScheduleEvent(to_candid_ScheduleEvent_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteActivity(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivity(arg0);
            return result;
        }
    }
    async deleteDocumentationEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocumentationEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocumentationEntry(arg0);
            return result;
        }
    }
    async deleteKidProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKidProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKidProfile(arg0);
            return result;
        }
    }
    async deleteOrphanage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrphanage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrphanage(arg0);
            return result;
        }
    }
    async deletePerson(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePerson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePerson(arg0);
            return result;
        }
    }
    async deleteProgram(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProgram(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProgram(arg0);
            return result;
        }
    }
    async deleteProgramMediaAttachment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProgramMediaAttachment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProgramMediaAttachment(arg0);
            return result;
        }
    }
    async deleteScheduleEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScheduleEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScheduleEvent(arg0);
            return result;
        }
    }
    async getActiveKidContext(): Promise<KidProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveKidContext();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveKidContext();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivity(arg0: string): Promise<Activity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivity(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivity(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKidProfile(arg0: string): Promise<KidProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKidProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKidProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrphanage(arg0: string): Promise<Orphanage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrphanage(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrphanage(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgram(arg0: string): Promise<Program | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgram(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgram(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivities();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivities();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDocumentationEntries(): Promise<Array<DocumentationEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocumentationEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocumentationEntries();
            return result;
        }
    }
    async listMyKidProfiles(): Promise<Array<KidProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyKidProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyKidProfiles();
            return result;
        }
    }
    async listOrphanages(): Promise<Array<Orphanage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrphanages();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrphanages();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPeople(): Promise<Array<Person>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPeople();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPeople();
            return result;
        }
    }
    async listProgramMediaAttachments(arg0: string): Promise<Array<ProgramMediaAttachment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProgramMediaAttachments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProgramMediaAttachments(arg0);
            return result;
        }
    }
    async listPrograms(): Promise<Array<Program>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPrograms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPrograms();
            return result;
        }
    }
    async listScheduleEvents(arg0: string): Promise<Array<ScheduleEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listScheduleEvents(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listScheduleEvents(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeProgramFromKid(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProgramFromKid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProgramFromKid(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async selectKidContext(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selectKidContext(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectKidContext(arg0);
            return result;
        }
    }
    async updateActivity(arg0: string, arg1: Activity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivity(arg0, to_candid_Activity_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivity(arg0, to_candid_Activity_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateDocumentationEntry(arg0: bigint, arg1: DocumentationEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocumentationEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocumentationEntry(arg0, arg1);
            return result;
        }
    }
    async updateOrphanage(arg0: string, arg1: Orphanage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrphanage(arg0, to_candid_Orphanage_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrphanage(arg0, to_candid_Orphanage_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePerson(arg0: bigint, arg1: Person): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePerson(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePerson(arg0, arg1);
            return result;
        }
    }
    async updateProgram(arg0: string, arg1: Program): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProgram(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProgram(arg0, arg1);
            return result;
        }
    }
    async updateScheduleEvent(arg0: string, arg1: ScheduleEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScheduleEvent(arg0, to_candid_ScheduleEvent_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScheduleEvent(arg0, to_candid_ScheduleEvent_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadProgramMediaAttachment(arg0: MediaAttachmentUpload): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProgramMediaAttachment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProgramMediaAttachment(arg0);
            return result;
        }
    }
}
function from_candid_Activity_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Orphanage_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Orphanage): Orphanage {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ScheduleEvent_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScheduleEvent): ScheduleEvent {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KidProfile]): KidProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Activity]): Activity | null {
    return value.length === 0 ? null : from_candid_Activity_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Orphanage]): Orphanage | null {
    return value.length === 0 ? null : from_candid_Orphanage_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Program]): Program | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    title: string;
    owner: Principal;
    isArchived: boolean;
    programId: string;
    orphanageId: [] | [string];
}): {
    id: string;
    status: string;
    title: string;
    owner: Principal;
    isArchived: boolean;
    programId: string;
    orphanageId?: string;
} {
    return {
        id: value.id,
        status: value.status,
        title: value.title,
        owner: value.owner,
        isArchived: value.isArchived,
        programId: value.programId,
        orphanageId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.orphanageId))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    region: string;
    constraints: string;
    secondaryContact: [] | [string];
    currentOccupancy: bigint;
    name: string;
    isActive: boolean;
    address: string;
    capacity: bigint;
    internalNotes: string;
    demographicNotes: string;
    primaryContact: string;
    priorityNeeds: string;
}): {
    id: string;
    region: string;
    constraints: string;
    secondaryContact?: string;
    currentOccupancy: bigint;
    name: string;
    isActive: boolean;
    address: string;
    capacity: bigint;
    internalNotes: string;
    demographicNotes: string;
    primaryContact: string;
    priorityNeeds: string;
} {
    return {
        id: value.id,
        region: value.region,
        constraints: value.constraints,
        secondaryContact: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.secondaryContact)),
        currentOccupancy: value.currentOccupancy,
        name: value.name,
        isActive: value.isActive,
        address: value.address,
        capacity: value.capacity,
        internalNotes: value.internalNotes,
        demographicNotes: value.demographicNotes,
        primaryContact: value.primaryContact,
        priorityNeeds: value.priorityNeeds
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    isArchived: boolean;
    endTimestamp: bigint;
    startTimestamp: bigint;
    programId: string;
    location: [] | [string];
}): {
    id: string;
    title: string;
    description: string;
    isArchived: boolean;
    endTimestamp: bigint;
    startTimestamp: bigint;
    programId: string;
    location?: string;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        isArchived: value.isArchived,
        endTimestamp: value.endTimestamp,
        startTimestamp: value.startTimestamp,
        programId: value.programId,
        location: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Orphanage>): Array<Orphanage> {
    return value.map((x)=>from_candid_Orphanage_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScheduleEvent>): Array<ScheduleEvent> {
    return value.map((x)=>from_candid_ScheduleEvent_n31(_uploadFile, _downloadFile, x));
}
function to_candid_Activity_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Activity): _Activity {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Orphanage_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Orphanage): _Orphanage {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ScheduleEvent_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScheduleEvent): _ScheduleEvent {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    title: string;
    owner: Principal;
    isArchived: boolean;
    programId: string;
    orphanageId?: string;
}): {
    id: string;
    status: string;
    title: string;
    owner: Principal;
    isArchived: boolean;
    programId: string;
    orphanageId: [] | [string];
} {
    return {
        id: value.id,
        status: value.status,
        title: value.title,
        owner: value.owner,
        isArchived: value.isArchived,
        programId: value.programId,
        orphanageId: value.orphanageId ? candid_some(value.orphanageId) : candid_none()
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    region: string;
    constraints: string;
    secondaryContact?: string;
    currentOccupancy: bigint;
    name: string;
    isActive: boolean;
    address: string;
    capacity: bigint;
    internalNotes: string;
    demographicNotes: string;
    primaryContact: string;
    priorityNeeds: string;
}): {
    id: string;
    region: string;
    constraints: string;
    secondaryContact: [] | [string];
    currentOccupancy: bigint;
    name: string;
    isActive: boolean;
    address: string;
    capacity: bigint;
    internalNotes: string;
    demographicNotes: string;
    primaryContact: string;
    priorityNeeds: string;
} {
    return {
        id: value.id,
        region: value.region,
        constraints: value.constraints,
        secondaryContact: value.secondaryContact ? candid_some(value.secondaryContact) : candid_none(),
        currentOccupancy: value.currentOccupancy,
        name: value.name,
        isActive: value.isActive,
        address: value.address,
        capacity: value.capacity,
        internalNotes: value.internalNotes,
        demographicNotes: value.demographicNotes,
        primaryContact: value.primaryContact,
        priorityNeeds: value.priorityNeeds
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    isArchived: boolean;
    endTimestamp: bigint;
    startTimestamp: bigint;
    programId: string;
    location?: string;
}): {
    id: string;
    title: string;
    description: string;
    isArchived: boolean;
    endTimestamp: bigint;
    startTimestamp: bigint;
    programId: string;
    location: [] | [string];
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        isArchived: value.isArchived,
        endTimestamp: value.endTimestamp,
        startTimestamp: value.startTimestamp,
        programId: value.programId,
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
